### ISSUE TITLE
try to improve result

### ISSUE THREAD

**Issue by Jiaqidtu** [Wi-sc/ViewFusion#4]
For the 3d generation, I can get a good result if I use some simple object like a chair, but I got really bad result when I try to generate a 3d model of a tree.
<img width="397" alt="image" src="https://github.com/Wi-sc/ViewFusion/assets/167117229/11cb691a-0e97-4c99-a0b2-f18ef396c758">

<img width="380" alt="image" src="https://github.com/Wi-sc/ViewFusion/assets/167117229/b40c78cd-649e-4bfd-bb10-ff017c406408">

Do you have any suggestions to improve the result?

**Comment by Wi-sc** [comment]
Hi there, thanks for your interest in our work. I noticed your input image is blurred. You could try a high-resolution image. 

And as you mentioned, current 3d generation work cannot handle complex objects well. It is still an open problem. :) Sorry for that.
