### ISSUE TITLE
Where to download ABODataset?

### ISSUE THREAD

**Issue by Runyu-Zhou05** [Wi-sc/ViewFusion#5]
Hi there! Thank you for your great work! In `zero123/generate_360_multi_view_autoregressive.py`, `ABODataset` was mentioned but I don't know where to download it (especially, what's the format of `angles.json`?). Also, the paths are absolute and `/home/ubuntu/workspace/zero123/3drec/data/real_images_zero123/` seems to be referring to `3drec/real_images`. Did you forget to fix this mistake? Lastly, I want to generate new views conditioned on multiple views with diverse azimuths, elevations and distances, not just with altering azimuths; is it possible in your implementation? Thank you very much!

**Comment by Wi-sc** [comment]
Hi @Runyu-Zhou05 

Thanks for your interest in our work. 

1. You can download the ABO dataset from the official website (https://amazon-berkeley-objects.s3.amazonaws.com/index.html). After you got the 3d model, you can pre-process the data to get the renderings using the scripts we provided. Sorry we cannot directly provide our renderings.

2. Yes, you can modify the path to the folder you created. Sorry for the issue.

3. Yes, you can. The multi-view generation code totally supports it.
